# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '51 3 * * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: |
        ./gfw-pac.py -f gfw.pac \
             -p "PROXY 127.0.0.1:18888; DIRECT" \
             --user-rule=custom-domains.txt \
             --direct-rule=direct-domains.txt \
             --localtld-rule=local-tlds.txt
        git add .
    - name: Set up SSH keys
      run: |
        mkdir ~/.ssh
        git config --global user.email "auto@xlch.me"
        git config --global user.name "Dark495Bot"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
    - name: Pull latest changes from the remote repo
      run: git pull -f origin $GITHUB_REF
    - name: Commit and push changes
      run: |
        if [[ $(git whatchanged -1 --format=oneline | wc -l) -gt 1 ]]; then
          git commit -m "Auto pushed by GitHub Actions";
          git push origin HEAD:$GITHUB_REF;
        fi
